@startuml

title 相関図

() Bluetooch as BLE
actor Player
[バット] as Bat
Player -d->Bat:振る

frame HoloLens {
    [Unity] --> [WinRT]:use
    [Unity] -->[Model]:use
}

WinRT .d.> BLE:接続
Player -d-> HoloLens :装着(頭)

frame UnlimitedHand{
    [Main] as UH_Main
    [Bluetooch-API] as UH_BLE
    [Sensor]as UH_Sensor
    UH_Main --> UH_BLE:use
    UH_Main --> UH_Sensor:use
}

Player <-d-> UnlimitedHand :装着(腕)
BLE .u.> UH_BLE:接続


frame BlueNinja{
    [Main]as BN_Main
    note left of BN_Main :作るもの?
    [BLE-API] as BSP_API
    [Sensor] as BN_Sensor
    BN_Main -->BSP_API:use
    BN_Main -->BN_Sensor:use
}

BLE .u.> BSP_API:接続
Bat -> BlueNinja :装着




@enduml
